using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyProduct("Ninject.Extensions.Prism: Ninject Extension for Prism")]
[assembly: AssemblyTitle("Ninject.Extension.Prism")]
[assembly: AssemblyCompany("DimensionalSoftware")]
[assembly: AssemblyVersion("4.0.0.0")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]

